[build]
  publish = "public"
  command = "sed -i \"s|__SUPABASE_URL__|$SUPABASE_URL|g\" public/js/*.js public/admin/*.js public/dashboard/*.js && sed -i \"s|__SUPABASE_ANON_KEY__|$SUPABASE_ANON_KEY|g\" public/js/*.js public/admin/*.js public/dashboard/*.js"

[[redirects]]
  from = "/admin"
  to = "/admin/application.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/application.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/*"
  to = "/dashboard/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
